/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzih_jni_Sm4Jni */

#ifndef _Included_com_hzih_jni_Sm4Jni
#define _Included_com_hzih_jni_Sm4Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzih_jni_Sm4Jni
 * Method:    setKey
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_hzih_jni_Sm4Jni_setKey
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_hzih_jni_Sm4Jni
 * Method:    encryptJni
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hzih_jni_Sm4Jni_encryptJni
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_hzih_jni_Sm4Jni
 * Method:    decryptJni
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hzih_jni_Sm4Jni_decryptJni
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
